### PR TITLE
Stop using the deprecated language class

### PR DESCRIPTION
**Pull request by StijnVrolijk**

### CODE REVIEW

**Review by WouterSioen — APPROVED** [review]

**Comment by Katrienvh** [comment]
you forgot one in` model.php`

**Comment by carakas** [comment]
@StijnVrolijk can you fix that? :)

**Comment by carakas** [comment]
@StijnVrolijk

**Comment by StijnVrolijk** [comment]
@Katrienvh @carakas everything should be okay now

**Comment by carakas** [comment]
@StijnVrolijk can you tag this and create a release?

**Comment by StijnVrolijk** [comment]
@carakas by this one

**Pull request merged**
